<?php

declare(strict_types=1);

define('DAY_IN_SECONDS', 86400);
define('COOKIEHASH', 'testcookiehash');

$test_options = [];

function get_option($name, $default = false)
{
    global $test_options;

    return array_key_exists($name, $test_options) ? $test_options[$name] : $default;
}

function wp_salt($scheme = 'auth')
{
    return 'test-salt-for-' . $scheme;
}

function wp_hash($data, $scheme = 'auth')
{
    return hash_hmac('md5', (string) $data, wp_salt($scheme));
}

require_once __DIR__ . '/../inc/PasswordProtected/Settings.php';
require_once __DIR__ . '/../inc/PasswordProtected/Auth.php';

use SFX\PasswordProtected\Auth;

function assert_true($condition, string $message): void
{
    if (!$condition) {
        fwrite(STDERR, "FAIL: {$message}\n");
        exit(1);
    }
}

$GLOBALS['blog_id'] = 1;
$hash = 'hashed:letmein';
$future = time() + 3600;

// 1. A cookie generated by Auth validates.
$cookie = Auth::generate_cookie($future, $hash);
assert_true(Auth::validate_cookie($cookie, $hash), '1: a freshly generated cookie validates');

// 2. Tampered HMAC fails.
[$sid, $exp, $hmac] = explode('|', $cookie);
assert_true(
    !Auth::validate_cookie($sid . '|' . $exp . '|' . strrev($hmac), $hash),
    '2: a tampered HMAC fails'
);

// 3. Tampered expiration fails.
assert_true(
    !Auth::validate_cookie($sid . '|' . ($future + 9999) . '|' . $hmac, $hash),
    '3: a tampered expiration fails'
);

// 4. Expired cookie fails.
$expired = Auth::generate_cookie(time() - 10, $hash);
assert_true(!Auth::validate_cookie($expired, $hash), '4: an expired cookie fails');

// 5. Malformed cookies fail. `null` means "read $_COOKIE", which is empty here.
foreach (['', 'garbage', 'a|b', 'a|b|c|d', null, ['array']] as $i => $bad) {
    assert_true(!Auth::validate_cookie($bad, $hash), "5: malformed cookie #{$i} fails");
}

// 6. Non-integer expiration fails.
assert_true(!Auth::validate_cookie($sid . '|9e99|' . $hmac, $hash), '6: a non-integer expiration fails');

// 7. Foreign site_id fails.
assert_true(!Auth::validate_cookie('bid_999|' . $exp . '|' . $hmac, $hash), '7: a foreign site_id fails');

// 8. A cookie signed against a different password hash fails.
assert_true(
    !Auth::validate_cookie($cookie, 'hashed:a-different-password'),
    '8: changing the password invalidates every existing cookie'
);

echo "OK\n";
