<?php

namespace SFX\Options\ACF;


class OptionsContact
{

	public static $menu_slug = 'sfx-contact-settings';

	public function __construct()
	{
		add_action('acf/init', [$this, 'add_acf_options_pages']);
		add_action('acf/init', [$this, 'register_fields']);
	}


	public function add_acf_options_pages()
  {

    // Make sure ACF is active
    if (function_exists('acf_add_options_page')) {

      $option_contact = acf_add_options_page(array(
        'page_title'  => __('Contact details', 'sfxtheme'),
        'menu_title'  => __('Contact details', 'sfxtheme'),
        'menu_slug'   => self::$menu_slug,
        'capability'  => 'edit_posts',
        'autoload'    => true,
        'icon_url' => 'dashicons-building',
      ));

      acf_add_options_sub_page(array(
        'page_title'   => __('Contact', 'sfxtheme'),
        'menu_title'   => __('Contact', 'sfxtheme'),
        'parent_slug'  => self::$menu_slug,
        'autoload'     => false
      ));
		}
	}

	public function register_fields()
	{
		// Your ACF field registration code here
		if (function_exists('acf_add_local_field_group')) {
			acf_add_local_field_group(array(
				'key' => 'group_5bd9b111b585c',
				'title' => 'Options Kontaktdaten',
				'fields' => array(
					array(
						'key' => 'field_5ce52b56aa8cc',
						'label' => 'Kontaktdaten / Rechtliche Angaben',
						'name' => '',
						'aria-label' => '',
						'type' => 'tab',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'acfe_permissions' => '',
						'placement' => 'top',
						'endpoint' => 0,
						'no_preference' => 0,
					),
					array(
						'key' => 'field_5bd9b11ef7cd7',
						'label' => 'Firmenname',
						'name' => 'company',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'acfe_save_meta' => 1,
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					array(
						'key' => 'field_5bd9b13ff7cd8',
						'label' => 'Geschäftsführer',
						'name' => 'director',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'acfe_save_meta' => 1,
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					array(
						'key' => 'field_62a5cf8f0a7d3',
						'label' => 'Straße / Nr.',
						'name' => 'street',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'acfe_save_meta' => 1,
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					array(
						'key' => 'field_62a5cfa80a7d4',
						'label' => 'PLZ',
						'name' => 'zip',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'acfe_save_meta' => 1,
						'default_value' => '',
						'maxlength' => 5,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					array(
						'key' => 'field_62a5cfb30a7d5',
						'label' => 'Ort',
						'name' => 'city',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '30',
							'class' => '',
							'id' => '',
						),
						'acfe_save_meta' => 1,
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					array(
						'key' => 'field_680b5223c5b35',
						'label' => 'Land',
						'name' => 'country',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'acfe_save_meta' => 1,
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					array(
						'key' => 'field_5d5e5c6087d45',
						'label' => 'Adresse formatiert',
						'name' => 'address',
						'aria-label' => '',
						'type' => 'wysiwyg',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'acfe_save_meta' => 1,
						'default_value' => '',
						'acfe_wysiwyg_height' => 300,
						'acfe_wysiwyg_max_height' => '',
						'acfe_wysiwyg_valid_elements' => '',
						'acfe_wysiwyg_custom_style' => '',
						'acfe_wysiwyg_disable_wp_style' => 0,
						'acfe_wysiwyg_autoresize' => 0,
						'acfe_wysiwyg_disable_resize' => 0,
						'acfe_wysiwyg_remove_path' => 0,
						'acfe_wysiwyg_menubar' => 0,
						'acfe_wysiwyg_transparent' => 0,
						'acfe_wysiwyg_merge_toolbar' => 0,
						'acfe_wysiwyg_custom_toolbar' => 0,
						'tabs' => 'all',
						'toolbar' => 'full',
						'media_upload' => 1,
						'delay' => 1,
						'acfe_wysiwyg_auto_init' => 0,
						'acfe_wysiwyg_min_height' => 300,
						'acfe_wysiwyg_toolbar_buttons' => array(),
					),
					array(
						'key' => 'field_5ee4bdfef08ed',
						'label' => 'Öffnungszeiten',
						'name' => 'opening',
						'aria-label' => '',
						'type' => 'wysiwyg',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'all',
						'toolbar' => 'full',
						'media_upload' => 1,
						'delay' => 1,
						'acfe_wysiwyg_auto_init' => 0,
						'acfe_wysiwyg_height' => 300,
						'acfe_wysiwyg_min_height' => 300,
						'acfe_wysiwyg_max_height' => '',
						'acfe_wysiwyg_valid_elements' => '',
						'acfe_wysiwyg_custom_style' => '',
						'acfe_wysiwyg_disable_wp_style' => 0,
						'acfe_wysiwyg_autoresize' => 0,
						'acfe_wysiwyg_disable_resize' => 0,
						'acfe_wysiwyg_remove_path' => 0,
						'acfe_wysiwyg_menubar' => 0,
						'acfe_wysiwyg_transparent' => 0,
						'acfe_wysiwyg_merge_toolbar' => 0,
						'acfe_wysiwyg_custom_toolbar' => 0,
						'acfe_wysiwyg_toolbar_buttons' => array(),
					),
					array(
						'key' => 'field_5d5e5cd087d46',
						'label' => 'Telefon',
						'name' => 'phone',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'acfe_save_meta' => 1,
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					array(
						'key' => 'field_5ee4d6915e938',
						'label' => 'Mobil',
						'name' => 'mobile',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'acfe_save_meta' => 1,
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					array(
						'key' => 'field_5ee4be48f08ee',
						'label' => 'Fax',
						'name' => 'fax',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'acfe_save_meta' => 1,
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					array(
						'key' => 'field_5e469d18895b5',
						'label' => 'E-Mail',
						'name' => 'email',
						'aria-label' => '',
						'type' => 'email',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'acfe_save_meta' => 1,
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					array(
						'key' => 'field_5bd9b1ddf7cde',
						'label' => 'Steuer-Nr.',
						'name' => 'tax-id',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'acfe_save_meta' => 1,
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					array(
						'key' => 'field_5bd9b1edf7cdf',
						'label' => 'UStId-Nr.',
						'name' => 'vat',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'acfe_save_meta' => 1,
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					array(
						'key' => 'field_5ce56ccd4bf06',
						'label' => 'Handelregister-Nr.',
						'name' => 'hrb',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'acfe_save_meta' => 1,
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					array(
						'key' => 'field_5ce56db71b36b',
						'label' => 'Registergericht',
						'name' => 'court',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'acfe_save_meta' => 1,
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					array(
						'key' => 'field_5ce56d2a1b36a',
						'label' => 'Datenschutzbeauftragter',
						'name' => 'dsb',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33',
							'class' => '',
							'id' => '',
						),
						'acfe_save_meta' => 1,
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					array(
						'key' => 'field_5ee4d5338ed7f',
						'label' => 'Google Maps Link',
						'name' => 'maplink',
						'aria-label' => '',
						'type' => 'link',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'acfe_save_meta' => 1,
						'return_format' => 'array',
					),
					array(
						'key' => 'field_5ee4bd54d3861',
						'label' => 'Filialen',
						'name' => '',
						'aria-label' => '',
						'type' => 'tab',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'acfe_permissions' => '',
						'placement' => 'top',
						'endpoint' => 0,
						'no_preference' => 0,
					),
					array(
						'key' => 'field_5e469db7bd139',
						'label' => 'Filialen/Standorte',
						'name' => 'contact_info',
						'aria-label' => '',
						'type' => 'repeater',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'acfe_save_meta' => 1,
						'acfe_repeater_stylised_button' => 0,
						'layout' => 'block',
						'pagination' => 0,
						'min' => 0,
						'max' => 0,
						'acfe_permissions' => '',
						'collapsed' => 'field_5d274552f0317',
						'button_label' => 'Filiale/Standort hinzufügen',
						'rows_per_page' => 20,
						'sub_fields' => array(
							array(
								'key' => 'field_5d274552f0317',
								'label' => 'Filialenbezeichnung',
								'name' => 'branch_title',
								'aria-label' => '',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'acfe_save_meta' => 1,
								'default_value' => '',
								'maxlength' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'parent_repeater' => 'field_5e469db7bd139',
							),
							array(
								'key' => 'field_5ee4bd308bd8e',
								'label' => 'Ansprechpartner',
								'name' => 'branch_contact_person',
								'aria-label' => '',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'acfe_save_meta' => 1,
								'default_value' => '',
								'maxlength' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'parent_repeater' => 'field_5e469db7bd139',
							),
							array(
								'key' => 'field_62a5d15b3d622',
								'label' => 'Straße / Nr.',
								'name' => 'branch_street',
								'aria-label' => '',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '25',
									'class' => '',
									'id' => '',
								),
								'acfe_save_meta' => 1,
								'default_value' => '',
								'maxlength' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'parent_repeater' => 'field_5e469db7bd139',
							),
							array(
								'key' => 'field_62a5d1743d623',
								'label' => 'PLZ',
								'name' => 'branch_zip',
								'aria-label' => '',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '20',
									'class' => '',
									'id' => '',
								),
								'acfe_save_meta' => 1,
								'default_value' => '',
								'maxlength' => 5,
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'parent_repeater' => 'field_5e469db7bd139',
							),
							array(
								'key' => 'field_62a5d1883d624',
								'label' => 'Stadt',
								'name' => 'branch_city',
								'aria-label' => '',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '25',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
								'parent_repeater' => 'field_5e469db7bd139',
							),
							array(
								'key' => 'field_680b531b7f1bc',
								'label' => 'Land',
								'name' => 'branch_country',
								'aria-label' => '',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '30',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
								'parent_repeater' => 'field_5e469db7bd139',
							),
							array(
								'key' => 'field_5bd9b184f7cd9',
								'label' => 'Adresse formatiert',
								'name' => 'branch_address',
								'aria-label' => '',
								'type' => 'wysiwyg',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '50',
									'class' => '',
									'id' => '',
								),
								'acfe_save_meta' => 1,
								'default_value' => '',
								'acfe_wysiwyg_height' => 300,
								'acfe_wysiwyg_max_height' => '',
								'acfe_wysiwyg_valid_elements' => '',
								'acfe_wysiwyg_custom_style' => '',
								'acfe_wysiwyg_disable_wp_style' => 0,
								'acfe_wysiwyg_autoresize' => 0,
								'acfe_wysiwyg_disable_resize' => 0,
								'acfe_wysiwyg_remove_path' => 0,
								'acfe_wysiwyg_menubar' => 0,
								'acfe_wysiwyg_transparent' => 0,
								'acfe_wysiwyg_merge_toolbar' => 0,
								'acfe_wysiwyg_custom_toolbar' => 0,
								'tabs' => 'all',
								'toolbar' => 'full',
								'media_upload' => 1,
								'delay' => 1,
								'acfe_wysiwyg_auto_init' => 0,
								'acfe_wysiwyg_min_height' => 300,
								'acfe_wysiwyg_toolbar_buttons' => array(),
								'parent_repeater' => 'field_5e469db7bd139',
							),
							array(
								'key' => 'field_5bdcad091c85e',
								'label' => 'Öffnungszeiten',
								'name' => 'branch_opening',
								'aria-label' => '',
								'type' => 'wysiwyg',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '50',
									'class' => '',
									'id' => '',
								),
								'acfe_save_meta' => 1,
								'default_value' => '',
								'acfe_wysiwyg_height' => 300,
								'acfe_wysiwyg_max_height' => '',
								'acfe_wysiwyg_valid_elements' => '',
								'acfe_wysiwyg_custom_style' => '',
								'acfe_wysiwyg_disable_wp_style' => 0,
								'acfe_wysiwyg_autoresize' => 0,
								'acfe_wysiwyg_disable_resize' => 0,
								'acfe_wysiwyg_remove_path' => 0,
								'acfe_wysiwyg_menubar' => 0,
								'acfe_wysiwyg_transparent' => 0,
								'acfe_wysiwyg_merge_toolbar' => 0,
								'acfe_wysiwyg_custom_toolbar' => 0,
								'tabs' => 'all',
								'toolbar' => 'full',
								'media_upload' => 1,
								'delay' => 1,
								'acfe_wysiwyg_auto_init' => 0,
								'acfe_wysiwyg_min_height' => 300,
								'acfe_wysiwyg_toolbar_buttons' => array(),
								'parent_repeater' => 'field_5e469db7bd139',
							),
							array(
								'key' => 'field_5bd9b1a4f7cda',
								'label' => 'Telefon',
								'name' => 'branch_phone',
								'aria-label' => '',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '50',
									'class' => '',
									'id' => '',
								),
								'acfe_save_meta' => 1,
								'default_value' => '',
								'maxlength' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'parent_repeater' => 'field_5e469db7bd139',
							),
							array(
								'key' => 'field_5bd9b1bff7cdc',
								'label' => 'Fax',
								'name' => 'branch_fax',
								'aria-label' => '',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '50',
									'class' => '',
									'id' => '',
								),
								'acfe_save_meta' => 1,
								'default_value' => '',
								'maxlength' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'parent_repeater' => 'field_5e469db7bd139',
							),
							array(
								'key' => 'field_5bd9b1b1f7cdb',
								'label' => 'Mobil',
								'name' => 'branch_mobile',
								'aria-label' => '',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '50',
									'class' => '',
									'id' => '',
								),
								'acfe_save_meta' => 1,
								'default_value' => '',
								'maxlength' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'parent_repeater' => 'field_5e469db7bd139',
							),
							array(
								'key' => 'field_5bd9b1cdf7cdd',
								'label' => 'E-Mail',
								'name' => 'branch_email',
								'aria-label' => '',
								'type' => 'email',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '50',
									'class' => '',
									'id' => '',
								),
								'acfe_save_meta' => 1,
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'parent_repeater' => 'field_5e469db7bd139',
							),
							array(
								'key' => 'field_6011560d0c064',
								'label' => 'Link zur Standortseite',
								'name' => 'branch_pagelink',
								'aria-label' => '',
								'type' => 'link',
								'instructions' => 'Hier ggf. Standort mit einer Standortseite verknüpfen.',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '50',
									'class' => '',
									'id' => '',
								),
								'acfe_save_meta' => 1,
								'return_format' => 'url',
								'parent_repeater' => 'field_5e469db7bd139',
							),
							array(
								'key' => 'field_5ce52c2f53cbc',
								'label' => 'Link Google Maps',
								'name' => 'branch_maplink',
								'aria-label' => '',
								'type' => 'link',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '50',
									'class' => '',
									'id' => '',
								),
								'acfe_save_meta' => 1,
								'return_format' => 'url',
								'parent_repeater' => 'field_5e469db7bd139',
							),
							array(
								'key' => 'field_600f02f2cefb1',
								'label' => 'Angaben für Standortkarte',
								'name' => 'branch_map',
								'aria-label' => '',
								'type' => 'group',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'acfe_save_meta' => 1,
								'layout' => 'block',
								// 'acfe_seamless_style' => 0,
								// 'acfe_group_modal' => 0,
								// 'acfe_group_modal_close' => 0,
								// 'acfe_group_modal_button' => '',
								// 'acfe_group_modal_size' => 'large',
								'parent_repeater' => 'field_5e469db7bd139',
								'sub_fields' => array(
									array(
										'key' => 'field_600f01fcddeee',
										'label' => 'Marker-Icon',
										'name' => 'branch_marker_icon',
										'aria-label' => '',
										'type' => 'image',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '20',
											'class' => '',
											'id' => '',
										),
										'uploader' => 'wp',
										'acfe_thumbnail' => 0,
										'return_format' => 'url',
										'preview_size' => 'medium',
										'library' => 'all',
										'min_width' => '',
										'min_height' => '',
										'min_size' => '',
										'max_width' => '',
										'max_height' => '',
										'max_size' => '',
										'mime_types' => '',
										'upload_folder' => '',
									),
									array(
										'key' => 'field_600f0dc0ad8e8',
										'label' => 'Marker-Titel',
										'name' => 'branch_marker_title',
										'aria-label' => '',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '20',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array(
										'key' => 'field_60104e30e684d',
										'label' => 'Titel-Position zum Marker',
										'name' => 'branch_map_titlepos',
										'aria-label' => '',
										'type' => 'select',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '20',
											'class' => '',
											'id' => '',
										),
										'choices' => array(
											'right' => 'rechts',
											'left' => 'links',
										),
										'default_value' => false,
										'allow_null' => 0,
										'multiple' => 0,
										'ui' => 0,
										'return_format' => 'value',
										'ajax' => 0,
										'placeholder' => '',
										'allow_custom' => 0,
										'search_placeholder' => '',
										'prepend' => '',
										'append' => '',
										'min' => '',
										'max' => '',
									),
									array(
										'key' => 'field_600f0223ddeef',
										'label' => 'Position-x',
										'name' => 'branch_map_posx',
										'aria-label' => '',
										'type' => 'number',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '20',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '%',
										'min' => '',
										'max' => '',
										'step' => '',
									),
									array(
										'key' => 'field_600f023cddef0',
										'label' => 'Position-y',
										'name' => 'branch_map_posy',
										'aria-label' => '',
										'type' => 'number',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '20',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '%',
										'min' => '',
										'max' => '',
										'step' => '',
									),
								),
							),
						),
					),
				),
				'location' => array(
					array(
						array(
							'param' => 'options_page',
							'operator' => '==',
							'value' => 'acf-options-contact',
						),
					),
				),
				'menu_order' => 17,
				'position' => 'normal',
				'style' => 'seamless',
				'label_placement' => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen' => array(
					0 => 'author',
					1 => 'featured_image',
					2 => 'discussion',
					3 => 'format',
					4 => 'the_content',
					5 => 'categories',
					6 => 'comments',
					7 => 'permalink',
					8 => 'revisions',
					9 => 'tags',
					10 => 'page_attributes',
					11 => 'excerpt',
					12 => 'slug',
					13 => 'send-trackbacks',
				),
				'active' => true,
				'description' => '',
				'show_in_rest' => 0,
				'acfe_autosync' => array(
					0 => 'php',
					1 => 'json',
				),
				'acfe_form' => 0,
				'acfe_display_title' => '',
				'acfe_permissions' => '',
				'acfe_meta' => '',
				'acfe_note' => '',
				'modified' => 1700509582,
				'acfe_categories' => array(
					'options' => 'Options',
				),
			));
		}
	}
}
